### ISSUE TITLE
Chainer or Pytorch

### ISSUE THREAD

**Issue by lahirufano** [espnet/espnet#82] opened 2018-01-31 10:24 UTC
Hi All, 

Is it possible to use only Pytorch as the backend? If not, could someone tell me the purpose of having two deep learning frameworks?

Thanks,
Lahiru

**Comment by sw005320** [comment] 2018-01-31 17:49
The current main programs uses chainer trainer/reporter functions, and it is not easy to make it run only with pytorch.

We're thinking of making these backends in more separately ways, but currently there are two reasons that these programs are in this shape.
1) we first made ESPnet with chainer, and added pytorch backend. We already had solid numbers with chainer, and wanted to reproduce the same result with pytorch. So, the pytorch backend aims to simply replace the original chainer version with function levels, and keeping the main programs (chainer reporter/trainer) same.
2) several functions (VGG-like layer and RNNLM integration) are not fully implemented in the pytorch backend, and chainer backend is still better in terms of the performance, and some recipes still use chainer as a main backend.

We notice that the current design is not great, and we're actually thinking of it. If you think this is very important, we'll make this item higher priority.

**Comment by lahirufano** [comment] 2018-02-01 09:07
Thanks for your detailed explanation Shinji. I think it'll be more attractive if these two backends are more independent. 

I recently read your journal paper on Hybrid CTC/Attention for E2E ASR, and currently looking to build some baselines and then to investigate research directions.  

Moreover, I like espnet's decision to stick with Kaldi for data prep. This allows us to easily built-in Kaldi tools which is not available in other E2E ASR frameworks. 

Thanks,
Lahiru

**Comment by sw005320** [comment] 2018-02-01 10:54
Thanks, Lahiru for your feedback. We'll definitely work on it in near future. Yes, this tool is a kind of Kaldi spin off, and we'll keep this style.

**Comment by sw005320** [comment] 2018-02-02 13:15
@ShigekiKarita @takaaki-hori @kan-bayashi , I think it's time to consider some refactoring. How do we proceed? I'm thinking of making a tag on the current version as a kind of stable version, as we almost finished all items in #35. Then, move to refactoring. Do you have any suggestions on it? @lahirufano, of course we welcome your input.

**Comment by kan-bayashi** [comment] 2018-02-21 04:54
To use the current version, it is necessary to update warp_ctc.
```bash
cd tools
rm -r warp-ctc
make warp-ctc
```

**Comment by arnold36** [comment] 2018-02-28 21:04
Could you please look into the resume training option for PyTorch that is not currently implemented (https://github.com/espnet/espnet/blob/master/src/asr/asr_pytorch.py#L218)? Does this mixed backend create an issue for resuming training in PyTorch?

**Comment by sw005320** [comment] 2018-03-01 20:39
@bobchennan has a similar problem and try to fix it. @kan-bayashi, do you use this resume function?

**Comment by kan-bayashi** [comment] 2018-06-13 08:17
This problem seems to be solved. I closed this issue.

**Closed by kan-bayashi** 2018-06-13 08:17 UTC

**Comment by fanlu** [comment] 2018-11-04 01:16
Is there any plan on this in roadmap 0.3? #444

**Comment by sw005320** [comment] 2018-11-05 02:38
I think we fixed the resume function for the PyTorch backend. If you're talking about the other issue, please tell me.
