### ISSUE TITLE
Is this current version (espnet 2022/09) supporting mac m1 chip?

### ISSUE THREAD

**Issue by lidl2019** [espnet/espnet#4710] opened 2022-10-12 09:36 UTC

**Comment by kamo-naoyuki** [comment] 2022-10-12 11:32
No. 

If your purpose is for DNN training, it's not compatible with Mac because some shell scripts don't work. You need to fix them.

I don't have M1 mac, so I can't check, but  the installation tool of espnet (`tools/Makefile`) or `pip install espnet` probably work with M1 mac( with `x86_64` using Rosetta 2).

In my understanding, pytorch=1.12 don't support GPU for M1 mac and requires the nightly version, but we didn't test  the nightly version with espnet.

**Comment by bmilde** [comment] 2023-02-10 13:41
I can confirm Espnet works on the Mac M1 for inference, just as on any other processor with device='cpu'. Support for the Mac GPU (device='mps') is a bit more tricky, but I did a couple of minor changes in my 'mac_m1_mps' branch to make model loading work for streaming models:  

https://github.com/speechcatcher-asr/espnet/tree/mac_m1_mps

You can try it out with:

`pip3 install git+https://github.com/speechcatcher-asr/espnet@mac_m1_mps`

Right now, a couple of ops are missing, for example:

```
    return forward_call(*input, **kwargs)
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/espnet2/layers/stft.py", line 173, in forward
    olens = (ilens - self.n_fft) // self.hop_length + 1
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/torch/_tensor.py", line 39, in wrapped
    return f(*args, **kwargs)
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/torch/_tensor.py", line 868, in __floordiv__
    return torch.floor_divide(self, other)
NotImplementedError: The operator 'aten::floor_divide' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

If you use PYTORCH_ENABLE_MPS_FALLBACK=1, it mentions another op:

`
/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/torch/functional.py:632: UserWarning: The operator 'aten::_fft_r2c' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)`

and ultimately stops out at,  I assume this is a bug in the fallback implementation:

```
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/espnet/nets/ctc_prefix_score.py", line 110, in __call__
    scoring_ids + self.idx_bo.repeat(1, n_hyps).view(-1, 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!
```

See https://github.com/pytorch/pytorch/issues/77764 , where ops are implemented depending on user feedback.

Btw Pytorch 1.12.1 already had limited support for the 'mps' device, its better in 1.13.1. I guess at some point enough ops will be available to support espnet, or the fallback implementation gets better. Maybe worth revisiting in a couple of months. Mps device would mainly target inference though.

**Comment by bmilde** [comment] 2023-02-10 14:22
Ok, got it one step ahead, ctc_prefix_score.py was checking the input x in the init function to determin the device and was only able to set it to cuda or cpu. I have that fixed in the branch now, but can't figure this one out yet:
```

Traceback (most recent call last):
  File "/Users/me/projects/speechcatcher/speechcatcher.py", line 174, in <module>
    recognize_microphone(speech2text, tag)
  File "/Users/me/projects/speechcatcher/speechcatcher.py", line 134, in recognize_microphone
    results = speech2text(speech=data, is_final=False)
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/espnet2/bin/asr_inference_streaming.py", line 322, in __call__
    nbest_hyps = self.beam_search(
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/espnet/nets/batch_beam_search_online.py", line 164, in forward
    ret = self.process_one_block(h, block_is_final, maxlen, maxlenratio)
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/espnet/nets/batch_beam_search_online.py", line 235, in process_one_block
    self.running_hyps = self.post_process(
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/espnet/nets/batch_beam_search.py", line 347, in post_process
    return self._batch_select(running_hyps, remained_ids)
  File "/Users/me/projects/speechcatcher/speechcatcher_env/lib/python3.10/site-packages/espnet/nets/batch_beam_search.py", line 46, in _batch_select
    score=hyps.score[ids],
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by sw005320** [comment] 2023-02-10 14:34
Thanks for the report.
It is a really valuable investigation.
It would be great if you post the progress.

**Comment by bmilde** [comment] 2023-02-10 15:12
Ok, somehow "ids" ended up being on "mps", but apparently needs to be on CPU (?) in batch_beam_search.py. 

With this, it actually runs on mps! But unfortunately it produces mangled/wrong output and it seems to be slower than with the CPU device (very likely due to all the missing mps ops).

Makes sense to check back in a couple of months with the next pytorch version, but for now it doesn't run properly on the "mps" device. The only thing I can think that could help right now is to reduce the complexity and only move the transformer block to mps.

**Closed** 2023-07-20 13:33 UTC
Labels: Installation
