### ISSUE TITLE
need help with CHIME4 recipe in both Espnet and Espnet2

### ISSUE THREAD

**Issue by 200987299** [espnet/espnet#1994] opened 2020-06-02 03:24 UTC
Dear all,

I have been trying to run the chime4 recipe in both espnet and espnet2 for a while. Does anyone feel comfortable running it without issues? I really want to get help from you. I have to debug every step forward and it is really frustrating. 

My first concern is that, based on the codes in espnet recipes, the WSJ0 directory structure under chime3/data/WSJ0 is different from the structure described in WSJ0 official documents. 

Secondly, I got a lot of errors like:
`fix_data_dir.sh: kept all 89844 utterances.
fix_data_dir.sh: old files are kept in dump/fbank_pitch/org/tr05_multi_noisy_si284/.backup
scripts/feats/feat_to_shape.sh --nj 32 --cmd run.pl dump/fbank_pitch/org/tr05_multi_noisy_si284/feats.scp dump/fbank_pitch/org/tr05_multi_noisy_si284/feats_shape
dt05_multi_isolated_1ch_track ,   
dump/fbank_pitch/org/dt05_multi_isolated_1ch_track
copy_data_dir
utils/copy_data_dir.sh: copied data from data/dt05_multi_isolated_1ch_track to dump/fbank_pitch/org/dt05_multi_isolated_1ch_track
utils/validate_text.pl: ERROR: file 'dump/fbank_pitch/org/dt05_multi_isolated_1ch_track/text' is empty or does not exist
`
Did anyone solved the same issue or anyone had successfully executed the CHIME4 recipe in Espnet or Espnet2? I am really appreciate your help.  

Thank you all for caring.

**Comment by sw005320** [comment] 2020-06-02 15:44
@yuekaizhang, could you answer it?
Also, probably better to revisit chime 4 with espnet2.
espnet2 is getting better and better now.

**Comment by yuekaizhang** [comment] 2020-06-02 18:23
@200987299, I am assuming you are runing chime4/asr1, rather than asr1_multich.
1. For dataset path chime4/chime3/data/WSJ0/wsj0, it is different with LDC93S6B, which is official wsj0. You should be careful about the variable $wsj0 and $wsj0_data in the recipe.
2. About your bugs, I downloaded the latest espnet, and run it from scrath. I didn't have your bugs.
I think it might be related to the 
`chime4_data=/export/corpora4/CHiME4/CHiME3 # JHU setup`
`wsj0=/export/corpora5/LDC/LDC93S6B            # JHU setup`
`wsj1=/export/corpora5/LDC/LDC94S13B           # JHU setup`

I paste how they look like in my side.
For chime4_data:
![image](https://user-images.githubusercontent.com/28823245/83555317-188ee600-a4dc-11ea-9d86-d332bf7587ff.png)

For wsj0:
![image](https://user-images.githubusercontent.com/28823245/83555388-33f9f100-a4dc-11ea-919c-c7e4c1950128.png)


Also, you could tell me which line of code in the recipe generating what errors. This would help me to fix your bugs.

**Comment by 200987299** [comment] 2020-06-04 02:45
@yuekaizhang Dear Yuekai, thank you very much for replying so fast. The current bug/ issue I am having now gives me this line:
`utils/copy_data_dir.sh: copied data from data/dt05_multi_isolated_1ch_track to dump/fbank_pitch/org/dt05_multi_isolated_1ch_track
utils/validate_text.pl: ERROR: file 'dump/fbank_pitch/org/dt05_multi_isolated_1ch_track/text' is empty or does not exist
`
I got this bug after I re-arranged my folders according to yours. Could you show me your deeper folder structure please? 

And about this bug, I got it after runing the script for an hour, after the script successfully finished running stage 1.

Thank you very much!
Bests
Di

**Comment by 200987299** [comment] 2020-06-04 02:45
> @yuekaizhang, could you answer it?
> Also, probably better to revisit chime 4 with espnet2.
> espnet2 is getting better and better now.

Thank you!

**Comment by 200987299** [comment] 2020-06-04 02:46
> @200987299, I am assuming you are runing chime4/asr1, rather than asr1_multich.
> 
>     1. For dataset path chime4/chime3/data/WSJ0/wsj0, it is different with LDC93S6B, which is official wsj0. You should be careful about the variable $wsj0 and $wsj0_data in the recipe.
> 
>     2. About your bugs, I downloaded the latest espnet, and run it from scrath. I didn't have your bugs.
>        I think it might be related to the
>        `chime4_data=/export/corpora4/CHiME4/CHiME3 # JHU setup`
>        `wsj0=/export/corpora5/LDC/LDC93S6B            # JHU setup`
>        `wsj1=/export/corpora5/LDC/LDC94S13B           # JHU setup`
> 
> 
> I paste how they look like in my side.
> For chime4_data:
> ![image](https://user-images.githubusercontent.com/28823245/83555317-188ee600-a4dc-11ea-9d86-d332bf7587ff.png)
> 
> For wsj0:
> ![image](https://user-images.githubusercontent.com/28823245/83555388-33f9f100-a4dc-11ea-919c-c7e4c1950128.png)
> 
> Also, you could tell me which line of code in the recipe generating what errors. This would help me to fix your bugs.
Dear Yuekai, thank you very much for replying so fast. The current bug/ issue I am having now gives me this line:
`utils/copy_data_dir.sh: copied data from data/dt05_multi_isolated_1ch_track to dump/fbank_pitch/org/dt05_multi_isolated_1ch_track utils/validate_text.pl: ERROR: file 'dump/fbank_pitch/org/dt05_multi_isolated_1ch_track/text' is empty or does not exist`
I got this bug after I re-arranged my folders according to yours. Could you show me your deeper folder structure please?

And about this bug, I got it after runing the script for an hour, after the script successfully finished running stage 1.

Thank you very much!
Bests
Di

**Comment by 200987299** [comment] 2020-06-04 02:47
> @200987299, I am assuming you are runing chime4/asr1, rather than asr1_multich.
> 
>     1. For dataset path chime4/chime3/data/WSJ0/wsj0, it is different with LDC93S6B, which is official wsj0. You should be careful about the variable $wsj0 and $wsj0_data in the recipe.
> 
>     2. About your bugs, I downloaded the latest espnet, and run it from scrath. I didn't have your bugs.
>        I think it might be related to the
>        `chime4_data=/export/corpora4/CHiME4/CHiME3 # JHU setup`
>        `wsj0=/export/corpora5/LDC/LDC93S6B            # JHU setup`
>        `wsj1=/export/corpora5/LDC/LDC94S13B           # JHU setup`
> 
> 
> I paste how they look like in my side.
> For chime4_data:
> ![image](https://user-images.githubusercontent.com/28823245/83555317-188ee600-a4dc-11ea-9d86-d332bf7587ff.png)
> 
> For wsj0:
> ![image](https://user-images.githubusercontent.com/28823245/83555388-33f9f100-a4dc-11ea-919c-c7e4c1950128.png)
> 
> Also, you could tell me which line of code in the recipe generating what errors. This would help me to fix your bugs.

Dear Yuekai, thank you very much for replying so fast. The current bug/ issue I am having now gives me this line:

'utils/copy_data_dir.sh: copied data from data/dt05_multi_isolated_1ch_track to dump/fbank_pitch/org/dt05_multi_isolated_1ch_track utils/validate_text.pl: ERROR: file 'dump/fbank_pitch/org/dt05_multi_isolated_1ch_track/text' is empty or does not exist'

I got this bug after I re-arranged my folders according to yours. Could you show me your deeper folder structure please?

And about this bug, I got it after runing the script for an hour, after the script successfully finished running stage 1.

Thank you very much!
Bests
Di

**Comment by 200987299** [comment] 2020-06-04 03:56
> > @200987299, I am assuming you are runing chime4/asr1, rather than asr1_multich.
> > ```
> > 1. For dataset path chime4/chime3/data/WSJ0/wsj0, it is different with LDC93S6B, which is official wsj0. You should be careful about the variable $wsj0 and $wsj0_data in the recipe.
> > 
> > 2. About your bugs, I downloaded the latest espnet, and run it from scrath. I didn't have your bugs.
> >    I think it might be related to the
> >    `chime4_data=/export/corpora4/CHiME4/CHiME3 # JHU setup`
> >    `wsj0=/export/corpora5/LDC/LDC93S6B            # JHU setup`
> >    `wsj1=/export/corpora5/LDC/LDC94S13B           # JHU setup`
> > ```
> > 
> > 
> > I paste how they look like in my side.
> > For chime4_data:
> > ![image](https://user-images.githubusercontent.com/28823245/83555317-188ee600-a4dc-11ea-9d86-d332bf7587ff.png)
> > For wsj0:
> > ![image](https://user-images.githubusercontent.com/28823245/83555388-33f9f100-a4dc-11ea-919c-c7e4c1950128.png)
> > Also, you could tell me which line of code in the recipe generating what errors. This would help me to fix your bugs.
> 
> Dear Yuekai, thank you very much for replying so fast. The current bug/ issue I am having now gives me this line:
> 
> 'utils/copy_data_dir.sh: copied data from data/dt05_multi_isolated_1ch_track to dump/fbank_pitch/org/dt05_multi_isolated_1ch_track utils/validate_text.pl: ERROR: file 'dump/fbank_pitch/org/dt05_multi_isolated_1ch_track/text' is empty or does not exist'
> 
> I got this bug after I re-arranged my folders according to yours. Could you show me your deeper folder structure please?
> 
> And about this bug, I got it after runing the script for an hour, after the script successfully finished running stage 1.
> 
> Thank you very much!
> Bests
> Di

Dear Yuekai,
The previous bug came out when I ran chime4 recipe in Espnet2. When I ran chime4 in Espnet1, I got this:
`stage 1: Feature Generation
copy_data_dir
apply_map.pl: undefined key F02_011C0204_STR.CH1_REAL in data-fbank/tr05_real_noisy/utt_map
` 
It seems the line 'utils/copy_data_dir.sh data/${x} data-fbank/${x}' in run.sh gives this error.

Bests
Di

**Comment by yuekaizhang** [comment] 2020-06-04 05:37
![image](https://user-images.githubusercontent.com/28823245/83718849-d5c82d80-a603-11ea-87bf-0f47dccaa0ff.png)
If this data structure is same with yours, pls tell me, I would check your bugs.

**Comment by 200987299** [comment] 2020-06-05 02:33
> ![image](https://user-images.githubusercontent.com/28823245/83718849-d5c82d80-a603-11ea-87bf-0f47dccaa0ff.png)
> If this data structure is same with yours, pls tell me, I would check your bugs.

Dear Yuekail,

I checked those folders, they are there. 
![dataStructure](https://user-images.githubusercontent.com/33377212/83830501-ea95e580-a717-11ea-8386-134b1b8e0aae.png)

Please help me!

Thank you
Di

**Comment by yuekaizhang** [comment] 2020-06-05 03:42
For espnet1,
![image](https://user-images.githubusercontent.com/28823245/83833691-842eaa00-a6ba-11ea-83b3-af30f8fc1716.png)
First run stage 0, then pls check you have the same wc result at this dir. 
Your error is might beacuse you didn't have that wav in your dataset.

For espnet2,
check data/dt05_simu_isolated_1ch_track, do you have "text" file?
Also check the two lines' output are correct 
https://github.com/espnet/espnet/blob/8c33d3774ecbdef47485dadacef5edc032ef5f50/egs2/chime4/asr1/local/data.sh#L62-L63

Btw, since many receipes share the same asr.sh in espnet2, sometimes modify the asr.sh for one receipe might introduce bugs for others. You should be careful when you use espnet2. Or you could use the histroy version when the receipe is merged.

**Comment by 200987299** [comment] 2020-06-05 06:55
> For espnet1,
> ![image](https://user-images.githubusercontent.com/28823245/83833691-842eaa00-a6ba-11ea-83b3-af30f8fc1716.png)
> First run stage 0, then pls check you have the same wc result at this dir.
> Your error is might beacuse you didn't have that wav in your dataset.
> 
> For espnet2,
> check data/dt05_simu_isolated_1ch_track, do you have "text" file?
> Also check the two lines' output are correct
> 
> https://github.com/espnet/espnet/blob/8c33d3774ecbdef47485dadacef5edc032ef5f50/egs2/chime4/asr1/local/data.sh#L62-L63
> 
> Btw, since many receipes share the same asr.sh in espnet2, sometimes modify the asr.sh for one receipe might introduce bugs for others. You should be careful when you use espnet2. Or you could use the histroy version when the receipe is merged.
> 
> Also, every line you should know its input and output, scripts in utils all have their usage explaination, it could help you find the reason.
Dear Yuekai,
Thank you for the suggestions, I will certainly check out utils. For now, I re-run the run.sh in espnet1, I got this result:
![Screenshot from 2020-06-05 14-51-30](https://user-images.githubusercontent.com/33377212/83845902-4ecaa080-a73c-11ea-8a0c-32ef0ec629e7.png)

It seems I am sort on something from the spk2utt, utt2spk and wav.scp. 


Bests
Di

**Comment by 200987299** [comment] 2020-06-05 09:40
> For espnet1,
> ![image](https://user-images.githubusercontent.com/28823245/83833691-842eaa00-a6ba-11ea-83b3-af30f8fc1716.png)
> First run stage 0, then pls check you have the same wc result at this dir.
> Your error is might beacuse you didn't have that wav in your dataset.
> 
> For espnet2,
> check data/dt05_simu_isolated_1ch_track, do you have "text" file?
> Also check the two lines' output are correct
> 
> https://github.com/espnet/espnet/blob/8c33d3774ecbdef47485dadacef5edc032ef5f50/egs2/chime4/asr1/local/data.sh#L62-L63
> 
> Btw, since many receipes share the same asr.sh in espnet2, sometimes modify the asr.sh for one receipe might introduce bugs for others. You should be careful when you use espnet2. Or you could use the histroy version when the receipe is merged.
> 
> Also, every line you should know its input and output, scripts in utils all have their usage explaination, it could help you find the reason.

Dear Yuekai,
May I ask how many files do you have under /export/corpora4/CHiME4/CHiME3/data/audio/16kHz/isolated_1ch_track ? I got 5952, which I am not so sure.

Bests
Di

**Comment by yuekaizhang** [comment] 2020-06-05 13:29
Sure, 
![image](https://user-images.githubusercontent.com/28823245/83881658-fa5cfc00-a70e-11ea-8d78-f679da533f1f.png)
Your text has 9600 items, while utt2spk only 7200.

**Comment by 200987299** [comment] 2020-06-06 08:08
> Sure,
> ![image](https://user-images.githubusercontent.com/28823245/83881658-fa5cfc00-a70e-11ea-8d78-f679da533f1f.png)
> Your text has 9600 items, while utt2spk only 7200.
> 
> Your dataset must be different with ours. My suggestion 1. Modify or redownload your data, I believe your problem would be addressed. 2. Modify the receipe to fit your data, which I may not have time to help.

Thank you Yuekai!

I am re-downloading it now. Hope this will fix the problem. Thanks for your time!

Bests
D

**Comment by 200987299** [comment] 2020-06-08 06:46
> Sure,
> ![image](https://user-images.githubusercontent.com/28823245/83881658-fa5cfc00-a70e-11ea-8d78-f679da533f1f.png)
> Your text has 9600 items, while utt2spk only 7200.
> 
> Your dataset must be different with ours. My suggestion 1. Modify or redownload your data, I believe your problem would be addressed. 2. Modify the receipe to fit your data, which I may not have time to help.

Dear Yuekai,

Sorry to @ you again, my script seems never passed stage 1. I re-checked my data, I got the same result as you presented before:
![Screenshot from 2020-06-08 13-18-07](https://user-images.githubusercontent.com/33377212/83999909-4a99bf80-a996-11ea-87e4-b5b2545e1a1e.png)

But, I still got error like:
![Screenshot from 2020-06-08 14-43-45](https://user-images.githubusercontent.com/33377212/84000036-80d73f00-a996-11ea-8f94-faf37acc97cb.png)

it seems that the code   `utils/fix_data_dir.sh data-fbank/${x}`  from stage 1:
`    for x in ${tasks}; do
        utils/copy_data_dir.sh data/${x} data-fbank/${x}
        utils/copy_data_dir.sh data/${x} data-stft/${x}
        steps/make_fbank_pitch.sh --nj 8 --cmd "${train_cmd}" --write_utt2num_frames true \
            data-fbank/${x} exp/make_fbank/${x} ${fbankdir}
        utils/fix_data_dir.sh data-fbank/${x}
    done`

Any idea how this could happen?

Bests
Di

**Comment by yuekaizhang** [comment] 2020-06-08 19:03
It looks like the same issue with the tr_05 dataset. This time your dt_05_real_isolated_1ch_track may miss something.
![image](https://user-images.githubusercontent.com/28823245/84069715-f7753c00-a998-11ea-868b-ebfaabe060fe.png)
If you do get the same result with me, my suggestion is to make a new copy of espnet and try to run script from scratch.  Since I can't reproduce your bug in my side, it's difficult to find the bugs.

**Comment by 200987299** [comment] 2020-06-09 01:18
> It looks like the same issue with the tr_05 dataset. This time your dt_05_real_isolated_1ch_track may miss something.
> ![image](https://user-images.githubusercontent.com/28823245/84069715-f7753c00-a998-11ea-868b-ebfaabe060fe.png)
> If you do get the same result with me, my suggestion is to make a new copy of espnet and try to run script from scratch. Since I can't reproduce your bug in my side, it's difficult to find the bugs.

Thank you! 

I will try it!

Bests
Di

**Closed** 2020-07-14 03:56 UTC
Labels: ASR, Bug

**Comment by 200987299** [comment] 2020-07-14 03:57
it an issue caused by not extracting data folders properly. Thanks for your time!
