### ISSUE TITLE
use aishell conformer v2 model，but not get any text？

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#2570] opened 2020-10-13 06:25 UTC
recog_wav  shell:
wac@waccuda:/data/espnet/egs/aishell/asr1$ recog_wav.sh --cmvn /home/wac/PycharmProjects/espnet_tts/model.v2/data/train_sp/cmvn.ark --lang_model /home/wac/PycharmProjects/espnet_tts/model.v2/exp/train_rnnlm_pytorch_lm/rnnlm.model.best  --recog_model /home/wac/PycharmProjects/espnet_tts/model.v2/exp/train_sp_pytorch_train_pytorch_conformer_kernel15_specaug/results/model.last10.avg.best --decode_config /home/wac/PycharmProjects/espnet_tts/model.v2/conf/decode_lm0.0.yaml /data/audio/data/data_aishell/wav/test/S0906/BAC009S0906W0125.wav

stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true decode/BAC009S0906W0125/data decode/BAC009S0906W0125/log decode/BAC009S0906W0125/fbank
steps/make_fbank_pitch.sh: moving decode/BAC009S0906W0125/data/feats.scp to decode/BAC009S0906W0125/data/.backup
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory decode/BAC009S0906W0125/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank_pitch.sh: Succeeded creating filterbank and pitch features for data
/data/espnet/egs/aishell/asr1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false decode/BAC009S0906W0125/data/feats.scp /home/wac/PycharmProjects/espnet_tts/model.v2/data/train_sp/cmvn.ark decode/BAC009S0906W0125/log decode/BAC009S0906W0125/dump
stage 2: Json Data Preparation
/data/espnet/egs/aishell/asr1/../../../utils/data2json.sh --feat decode/BAC009S0906W0125/dump/feats.scp decode/BAC009S0906W0125/data decode/BAC009S0906W0125/dict
/data/espnet/egs/aishell/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 decode/BAC009S0906W0125/dump/feats.scp decode/BAC009S0906W0125/data/tmp-h2ViK/input_1/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding

Recognized text: 

Finished

**### and  i  use model.v1(Transformer result (default transformer with initial learning rate = 1.0 and epochs = 50)
model link: https://drive.google.com/open?id=1BIQBpLRRy3XSMT5IRxnLcgLMirGzu8dg),  get correct results:**

stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 1 --write_utt2num_frames true decode/BAC009S0906W0125/data decode/BAC009S0906W0125/log decode/BAC009S0906W0125/fbank
steps/make_fbank_pitch.sh: moving decode/BAC009S0906W0125/data/feats.scp to decode/BAC009S0906W0125/data/.backup
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory decode/BAC009S0906W0125/data
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank_pitch.sh: Succeeded creating filterbank and pitch features for data
/data/espnet/egs/aishell/asr1/../../../utils/dump.sh --cmd run.pl --nj 1 --do_delta false decode/BAC009S0906W0125/data/feats.scp /home/wac/PycharmProjects/espnet_tts/model.v1/data/train_sp/cmvn.ark decode/BAC009S0906W0125/log decode/BAC009S0906W0125/dump
stage 2: Json Data Preparation
/data/espnet/egs/aishell/asr1/../../../utils/data2json.sh --feat decode/BAC009S0906W0125/dump/feats.scp decode/BAC009S0906W0125/data decode/BAC009S0906W0125/dict
/data/espnet/egs/aishell/asr1/../../../utils/feat_to_shape.sh --cmd run.pl --nj 1 --filetype  --preprocess-conf  --verbose 0 decode/BAC009S0906W0125/dump/feats.scp decode/BAC009S0906W0125/data/tmp-4KbGS/input_1/shape.scp
sym2int.pl: replacing X with 1
** Replaced 1 instances of OOVs with 1
stage 3: Decoding

Recognized text: 公积金松绑接棒施压房价下跌动力趋缓至搜狐财经

**how can inference with recog_wav.sh and with .py?**

**Comment by wac81** [comment] 2020-10-14 08:04
anybody knows why？

**Comment by sw005320** [comment] 2020-10-14 16:47
I don't know what happened, but we're now intensively working on conformer, and @pengchengguo will update a model soon.
So, it can be fixed in the near future.

**Comment by pengchengguo** [comment] 2020-10-14 23:36
Hi Arthur,

Sorry didn't notice your issue on time. I tested on my local machine and found it may caused by the wrong model file. I will upload a new model soon.

**Comment by pengchengguo** [comment] 2020-10-15 00:54
The new model link: https://drive.google.com/file/d/1pOhwj6JFqVyt5quW7BKWfJ3vfPFRoxpQ/view. I remove the original one and will make a PR ASAP.

**Comment by wac81** [comment] 2020-10-15 03:20
thanks, i will try it

**Closed** 2020-10-15 10:51 UTC
Labels: ASR, Bug, ESPnet1
