### ISSUE TITLE
Travis CI (error: travis-sphinx build) 

### ISSUE THREAD

**Issue by takaaki-hori** [espnet/espnet#97] opened 2018-02-12 18:56 UTC
@kan-bayashi @ShigekiKarita @sw005320 
I got the following error message when testing my pull request #95 with Travis CI. 
Do you have any ideas to pass this test?

$ travis-sphinx build --source=doc --nowarn
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/travis-sphinx", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/travis_sphinx/build.py", line 39, in build
    if sphinx.build_main(args + [source, outdir]):
AttributeError: 'module' object has no attribute 'build_main'
The command "travis-sphinx build --source=doc --nowarn" exited with 1.

**Comment by kan-bayashi** [comment] 2018-02-13 01:49
@takaaki-hori This error caused by the new version Sphinx (1.7>=).
It can be solved by modifying `doc/requirements.txt` as follows:
```
#Before
Sphinx>=1.6.5

# After
Sphinx==1.6.5
```

**Comment by sw005320** [comment] 2018-02-13 02:50
thanks. can you push this in the main repo?

**Comment by sw005320** [comment] 2018-02-13 12:13
It seems that #98 fixed this issue, and I close it.

**Closed by sw005320** 2018-02-13 12:13 UTC
