### ISSUE TITLE
can't synthesis good voice

### ISSUE THREAD

**Issue by 1nlplearner** [espnet/espnet#5257] opened 2023-06-26 03:54 UTC
Hi,
I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice.
so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice.
any advice?

**Comment by 1nlplearner** [comment] 2023-06-26 08:46
my token file is in dump/token_list/mixphn_none, is there any operation on the token path?

**Comment by iamanigeeit** [comment] 2023-06-26 13:23
> Hi, I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice. so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice. any advice?

I think you should use a multilingual model like VITS instead. Even if you use IPA for phonemes, different languages will pronounce them differently.

**Comment by 1nlplearner** [comment] 2023-06-27 03:26
> 

maybe token path is not a problem, there 300 chinese phonemes and 70 english phonemes in token list, I reduce half of english phonemes and all of english phonemes, the model can synthesis voice
why vits can process multilingual synthesis but fs2 can't,
thanks

**Comment by 1nlplearner** [comment] 2023-06-27 03:27
> > Hi, I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice. so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice. any advice?
> 
> I think you should use a multilingual model like VITS instead. Even if you use IPA for phonemes, different languages will pronounce them differently.

maybe token path is not a problem, there 300 chinese phonemes and 70 english phonemes in token list, I reduce half of english phonemes and all of english phonemes, the model can synthesis voice

**Comment by 1nlplearner** [comment] 2023-06-27 03:28
> 



> > Hi, I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice. so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice. any advice?
> 
> I think you should use a multilingual model like VITS instead. Even if you use IPA for phonemes, different languages will pronounce them differently.

**Comment by 1nlplearner** [comment] 2023-06-27 03:29
> > Hi, I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice. so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice. any advice?
> 
> I think you should use a multilingual model like VITS instead. Even if you use IPA for phonemes, different languages will pronounce them differently.

maybe token path is not a problem, there 300 chinese phonemes and 70 english phonemes in token list, I reduce half of english phonemes and all of english phonemes, the model can synthesis voice
why vits can process multilingual synthesis but fs2 can't,
thanks

**Comment by 1nlplearner** [comment] 2023-06-27 09:24
> 



> > > > Hi, I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice. so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice. any advice?
> > > 
> > > 
> > > I think you should use a multilingual model like VITS instead. Even if you use IPA for phonemes, different languages will pronounce them differently.
> > 
> > 
> > maybe token path is not a problem, there 300 chinese phonemes and 70 english phonemes in token list, I reduce half of english phonemes and all of english phonemes, the model can synthesis voice why vits can process multilingual synthesis but fs2 can't, thanks
> 
> Hmm, i see that FS2 should be able to do multilingual synthesis. Did you specify `langs: 2` in the config and `lid` of each utterance during training and inference?

no, I just put chinese phonemes and english phonemes in text file, and run stage 4 to get token list
but the problem is not multilinguage, I just use aishell3 data and use mixed token list, I meet the same problem

**Comment by iamanigeeit** [comment] 2023-06-27 13:03
> > 
> 
> > > > > Hi, I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice. so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice. any advice?
> > > > 
> > > > 
> > > > I think you should use a multilingual model like VITS instead. Even if you use IPA for phonemes, different languages will pronounce them differently.
> > > 
> > > 
> > > maybe token path is not a problem, there 300 chinese phonemes and 70 english phonemes in token list, I reduce half of english phonemes and all of english phonemes, the model can synthesis voice why vits can process multilingual synthesis but fs2 can't, thanks
> > 
> > 
> > Hmm, i see that FS2 should be able to do multilingual synthesis. Did you specify `langs: 2` in the config and `lid` of each utterance during training and inference?
> 
> no, I just put chinese phonemes and english phonemes in text file, and run stage 4 to get token list but the problem is not multilinguage, I just use aishell3 data and use mixed token list, I meet the same problem

I don't understand what you are trying to do and how...
1) Do you want your model to generate Mandarin from Mandarin text + English from English text? Or generate mixed sentences like "这个很cool" ?
2) The token_list should not be a problem. If it's auto-generated it should cover all possible phonemes. Maybe you can upload your token_list.

**Comment by 1nlplearner** [comment] 2023-06-27 13:19
> > > 
> > 
> > 
> > > > > > Hi, I have trained a good fs2 model based on aishell3, and I want to train a bilingual model, so I add VCTK corpus, use G2p_en to convert word to phoneme. I get a mix phoneme token list from mix text, but the bilingual model can't synthesis meaningful voice. so I did some experiments, I found that token list may be a problem, I retrain pervious good fs2 model using mix token list, the model can't synthesis meaningful voice. any advice?
> > > > > 
> > > > > 
> > > > > I think you should use a multilingual model like VITS instead. Even if you use IPA for phonemes, different languages will pronounce them differently.
> > > > 
> > > > 
> > > > maybe token path is not a problem, there 300 chinese phonemes and 70 english phonemes in token list, I reduce half of english phonemes and all of english phonemes, the model can synthesis voice why vits can process multilingual synthesis but fs2 can't, thanks
> > > 
> > > 
> > > Hmm, i see that FS2 should be able to do multilingual synthesis. Did you specify `langs: 2` in the config and `lid` of each utterance during training and inference?
> > 
> > 
> > no, I just put chinese phonemes and english phonemes in text file, and run stage 4 to get token list but the problem is not multilinguage, I just use aishell3 data and use mixed token list, I meet the same problem
> 
> I don't understand what you are trying to do and how...
> 
> 1. Do you want your model to generate Mandarin from Mandarin text + English from English text? Or generate mixed sentences like "这个很cool" ?
> 2. The token_list should not be a problem. If it's auto-generated it should cover all possible phonemes. Maybe you can upload your token_list.

1.generate mixed sentences like "这个很cool"
2.[tokens.txt](https://github.com/espnet/espnet/files/11882569/tokens.txt)
3.and this is my dev data which adding extension name ".txt" for uploading to github[text.txt](https://github.com/espnet/espnet/files/11882590/text.txt)

**Comment by 1nlplearner** [comment] 2023-06-28 06:37
sorry, I make a mistake, the problem is caused by code bug, pitch and energy don't be trained, i'm so stupid.

**Comment by iamanigeeit** [comment] 2023-06-28 08:52
tokens.txt looks ok. If the issue is solved, you can close the issue.

**Closed** 2023-06-30 09:28 UTC
