### ISSUE TITLE
FastSpeech2 support

### ISSUE THREAD

**Issue by WhiteFu** [espnet/espnet#2019] opened 2020-06-11 01:53 UTC
Hello, I find an interested paper(https://arxiv.org/pdf/2006.04558.pdf) called FastSpeech2.   It is an advanced version of FastSpeech, which eliminates the teacher model and directly combines PWG training to generate speech directly from text.  The results of the paper show that the phonetic quality and synthesis speed of speech are good.  It's great if espnet support FastSpeech2 :D. @kan-bayashi :))

**Comment by sw005320** [comment] 2020-06-11 12:01
Yes, we are actually considering it. We have several feature requests for TTS and try to make a plan for it.

If someone is interested in this project, please let us know it (through this issue or directly send an email to me (shinjiw@ieee.org)).
We're looking for a collaborator!

**Comment by WhiteFu** [comment] 2020-06-12 02:41
> Yes, we are actually considering it. We have several feature requests for TTS and try to make a plan for it.
> 
> If someone is interested in this project, please let us know it (through this issue or directly send an email to me ([shinjiw@ieee.org](mailto:shinjiw@ieee.org))).
> We're looking for a collaborator!

That's great, it's nice to see the implementation in this repo.

**Comment by rishikksh20** [comment] 2020-06-12 14:35
@sw005320 I am currently working on Fastspeech 2 and 2s on my private repo Fastspeech which is adapted from Espnet , once I successfully replicate the paper I will public that repo and will also love to raise PR here. But it will take time because I have only one gtx 1080 GPU.

**Comment by sw005320** [comment] 2020-06-12 16:06
> @sw005320 I am currently working on Fastspeech 2 and 2s on my private repo Fastspeech which is adapted from Espnet , once I successfully replicate the paper I will public that repo and will also love to raise PR here. But it will take time because I have only one gtx 1080 GPU.

This is very cool.
I think once you make some PRs with somehow it's working, the other developers or my colleagues could help your development, and we could accelerate it.

**Comment by rishikksh20** [comment] 2020-06-16 23:11
@sw005320 I think I have completed runnable the implementation of FastSpeech 2 in my repo but only problem what I get is the number of trainable parameters in my implementation it is 24.3 M and in fastspeech 2 paper author mentioned 27 M parameters. Though I am currently training my model to see actual success but here is my Model blueprint :
```
Trainable Parameters: 24.315M
FeedForwardTransformer(
  (encoder): Encoder(
    (embed): Sequential(
      (0): Embedding(56, 256, padding_idx=0)
      (1): ScaledPositionalEncoding(
        (dropout): Dropout(p=0.2, inplace=False)
      )
    )
    (encoders): MultiSequential(
      (0): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
      (1): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
      (2): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
      (3): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
    )
  )
  (duration_predictor): DurationPredictor(
    (conv): ModuleList(
      (0): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): ReLU()
        (2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (3): Dropout(p=0.5, inplace=False)
      )
      (1): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): ReLU()
        (2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (3): Dropout(p=0.5, inplace=False)
      )
    )
    (linear): Linear(in_features=256, out_features=1, bias=True)
  )
  (energy_predictor): EnergyPredictor(
    (predictor): VariancePredictor(
      (conv): ModuleList(
        (0): Sequential(
          (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): ReLU()
          (2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (3): Dropout(p=0.5, inplace=False)
        )
        (1): Sequential(
          (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): ReLU()
          (2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (3): Dropout(p=0.5, inplace=False)
        )
      )
      (linear): Linear(in_features=256, out_features=1, bias=True)
    )
  )
  (pitch_predictor): PitchPredictor(
    (predictor): VariancePredictor(
      (conv): ModuleList(
        (0): Sequential(
          (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): ReLU()
          (2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (3): Dropout(p=0.5, inplace=False)
        )
        (1): Sequential(
          (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): ReLU()
          (2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (3): Dropout(p=0.5, inplace=False)
        )
      )
      (linear): Linear(in_features=256, out_features=1, bias=True)
    )
  )
  (length_regulator): LengthRegulator()
  (decoder): Encoder(
    (embed): Sequential(
      (0): ScaledPositionalEncoding(
        (dropout): Dropout(p=0.2, inplace=False)
      )
    )
    (encoders): MultiSequential(
      (0): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
      (1): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
      (2): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
      (3): EncoderLayer(
        (self_attn): MultiHeadedAttention(
          (linear_q): Linear(in_features=256, out_features=256, bias=True)
          (linear_k): Linear(in_features=256, out_features=256, bias=True)
          (linear_v): Linear(in_features=256, out_features=256, bias=True)
          (linear_out): Linear(in_features=256, out_features=256, bias=True)
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (feed_forward): MultiLayeredConv1d(
          (w_1): Conv1d(256, 1024, kernel_size=(9,), stride=(1,), padding=(4,))
          (w_2): Conv1d(1024, 256, kernel_size=(1,), stride=(1,))
          (dropout): Dropout(p=0.2, inplace=False)
        )
        (norm1): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.2, inplace=False)
      )
    )
  )
  (feat_out): Linear(in_features=256, out_features=80, bias=True)
  (duration_criterion): DurationPredictorLoss(
    (criterion): MSELoss()
  )
  (energy_criterion): EnergyPredictorLoss(
    (criterion): MSELoss()
  )
  (pitch_criterion): PitchPredictorLoss(
    (criterion): MSELoss()
  )
  (criterion): L1Loss()
)
```
Do let me know if you find any flaw in it.

**Comment by sw005320** [comment] 2020-06-16 23:26
Thanks! 
I think that would not be a big deal, but yes, I agree that we should make it close to the original paper's model as much as possible.
@kan-bayashi, do you have some comments?

**Comment by kan-bayashi** [comment] 2020-06-17 04:44
Great! I've not yet read FastSpeech 2 paper in detail (I am struggling with DCASE challenge now). I will try to find the difference through reading the paper.

**Comment by rishikksh20** [comment] 2020-06-18 03:59
Ok, I have trained the model till 40k steps with a batch size of 16 on GTX 1080, training seems fine so far. 
At 40k, audio (reconstructed using griffin Lim) is clearly understandable with some artifacts. 
Duration predictor and energy predictor are also working like a charm but pitch predictor is yet not trained well.

**Comment by dathudeptrai** [comment] 2020-06-18 13:42
@rishikksh20 can you share ur samples.

@kan-bayashi I just finished FastSpeech2 training, with batch_size 16 and the model convergence at 150k steps. I also uploaded the samples (out of training scope, i get on BBC news) here (https://dathudeptrai.github.io/TensorflowTTS/) to compare with FastSpeech1 and Tacotron2. Hope you can implement FastSpeech2 on this repo. Btw, how about ur DCASE challenge :D, when it finish?

**Comment by rishikksh20** [comment] 2020-06-18 20:10
@dathudeptrai Checkout samples here:
https://github.com/rishikksh20/fastspeech2_samples
Meanwhile I have some questions regarding your Fastspeech  2 implementation that I will ask on your repo .

**Comment by ming024** [comment] 2020-07-04 07:28
@sw005320 I just finished my PyTorch implementation of [FastSpeech2](https://github.com/ming024/FastSpeech2).

The implementation mostly follows the paper. You can find my samples [here](https://ming024.github.io/FastSpeech2/). I think it is good enough but still slightly inferior to @dathudeptrai 's implementation.

**Comment by dathudeptrai** [comment] 2020-07-04 07:51
@ming024 i will take a look ur implementation and help you reproduce my results. BTW, it's hard to compared ur samples and my samples since you using **waveglow** as vocoder which is much **larger** and **slower** than the vocoder i'm using (MB-melgan). Quick glance ur samples, it's ok but somehow i feel there is no **stress**, i guess the problem is ur f0 predicted is overfit or it always predict almost the same value in the real inference. I need some time to see ur detail implementation :D, greate work :D.

**Comment by rishikksh20** [comment] 2020-07-04 19:39
Checkout I got decent result by combining MelGAN and WaveGlow with FastSpeech 2 trained @ 58k step with batch of 16 here:
https://colab.research.google.com/drive/1dmGAR0C9xPSFT0G_PEsBlWR7Vatc3N5U?usp=sharing
My implementation based on ESPNet's Fastspeech.

**Comment by sw005320** [comment] 2020-07-06 17:31
Thanks, @rishikksh20!
Are you still interested in contributing espnet?

**Comment by rishikksh20** [comment] 2020-07-06 17:48
@sw005320 Yes, I just at last stage of finish up FastSpeech2 at my repo, then I will work on ESPNet. Actually, architectural changes are quite simple only challenge is to incorporate the extra pre-processing of FastSpeech2 (`energy and pitch calculation`) with espnet's pre-processing. I will work on this and probably raise PR around this weekend.

**Comment by sw005320** [comment] 2020-07-06 17:58
Many thanks.
We actually want to discuss how we proceed with it.
As you may know, now we try to switch from espnet1 to espnet2 and want to think of developing on new implementations in espnet2 as much as possible.
Espnet2 does not change the internal model description and high-level concept is similar but it makes the development easy, simple, and scalable. @kan-bayashi is working on porting several TTS techniques and recipes. If you think of implementing your Fastspeech2 in espnet2, that is great, but I also don’t want to force you to do it.

**Comment by rishikksh20** [comment] 2020-07-06 18:42
@sw005320 Frankly, I think it's good decision as espnet1 seems very confusing, too many functions and jumbled, Kaldi & Chainer like dependencies make it more difficult to understand proper structure for newbie. Great to see new development approach as espnet2, it's much more pytorch friendly structure and removing Kaldi is big relief.
On point I don't have any problem to implement FastSpeech2 with either espnet1 or espnet2 as I have complete understanding of espnet1 structure and I think It will not take much time to understand new espnet2 structure. 
But for espnet2 this https://github.com/espnet/espnet/pull/2149 to be merge first.

**Comment by sw005320** [comment] 2020-07-06 18:56
> But for espnet2 this #2149 to be merge first.

Yes.
It will be merged soon.

**Comment by kan-bayashi** [comment] 2020-07-12 03:19
Hey guys, thank you for sharing great samples.
I finished the initial setup of ESPnet2 TTS. so I will start to implement FastSpeech2.

**Comment by kan-bayashi** [comment] 2020-07-12 03:36
I briefly checked @ming024 and @dathudeptrai implementation.
It seems that the main difference is the quantization of f0 and energy.
Did you check the effectiveness of the quantization? @ming024 @dathudeptrai

**Comment by dathudeptrai** [comment] 2020-07-12 03:40
@kan-bayashi yes i checked. The way you using f0/energy is the key to reproduce fastspeech2. If ur f0/energy overfit too much, ur samples is still ok but as i said above, the samples tend to be no **stress**

**Comment by kan-bayashi** [comment] 2020-07-12 04:10
@dathudeptrai Thanks. So your conclusion is quantization is not needed?

**Comment by dathudeptrai** [comment] 2020-07-12 04:16
@kan-bayashi quantization is just a one way to using f0/energy. The most important thing is the range of f0/energy and the number of bins.  The paper use n_bins = 256 but not mention about the range min max. In my experiment, if f0 in range [0, 7600] and n_f0_bins = 256, based on the valid loss, my f0 has deviation around 6-10 bins :)) that is too much and explain why on the real inference, the audio is not good and almost no **stress**. I think if you want implement as paper said, you should tune n_bins and min/max range of f0/energy.

**Comment by kan-bayashi** [comment] 2020-07-12 04:27
I see. F0 range is very important to avoid half pitch or double pitch.
We need to tune the range w.r.t. the target speaker as the same as voice conversion.
(Extract f0 -> check histogram -> refine the F0 range).
For example, in this case, 140 - 340.
<img width="628" alt="スクリーンショット 2020-07-12 午後1 26 04" src="https://user-images.githubusercontent.com/22779813/87238871-43f1e280-c443-11ea-97bd-306510128fb9.png">

**Comment by dathudeptrai** [comment] 2020-07-12 04:44
@kan-bayashi yeah, i also tried to clip f0 to 40> 400 based on historam visualization then take log(f0) then quantization to 256 unique value. Note that we use the real log(f0) to train, when inference we just need to lookup it into 256 value. But in my mind, the real important factor is the a = (log(f0_max) - log(40)) / n_bins. For example, f0_max = 400, f0_min = 40, n_bins = 256 then a = (2.6 - 1.6) / 256 = 0.004. That mean ur average mse loss should be <= 0.004 ^ 2 to make average f0  deviation <= 1.

**Comment by kan-bayashi** [comment] 2020-07-12 04:47
Yeah, maybe the use of large bins with adjusted range brings improvement but makes it difficult to predict.
It seems that there is a trade-off.

**Comment by dathudeptrai** [comment] 2020-07-12 04:53
@kan-bayashi if  you can't make it work as paper suggest :)), let work together to make our implementation synchronized :)). Since my framework now support TFLIte for inference on mobile/low-end devices so it's good if user want to training by pytorch but still want to deploy on mobile devices :D.

**Comment by rishikksh20** [comment] 2020-07-12 08:08
@kan-bayashi actual problem is to train f0 and energy without overfitting, I did 5 experiments like `adjusting different range for bins, use normalized f0 and energy, changing the threshold to calculate f0, etc` to train f0 and energy differently with exact paper details but the only problem in all is after 60k (batch=16, accum_grad=4) both variation predictor start overfitting and after 120k steps samples start to degrade. Using spectral denoising similar to Waveglow helps to improve sample quality. 
What I thought that train Variation Adaptor 60 to 80k steps with MSE and after the 80k stop variation adaptor train or maybe apply some delay and instead of using ground-truth f0 and energy to train a mel use predicted f0 and energy to train a mel.

**Comment by dathudeptrai** [comment] 2020-07-12 08:12
@rishikksh20 you can not use predicted f0/energy to train since it doesn't have gradient unless you train fp/energy the same as my repo.

**Comment by rishikksh20** [comment] 2020-07-12 08:17
> @rishikksh20 you can not use predicted f0/energy to train since it doesn't has gradient cause by quantization step unless you train fp/energy the same as my repo.

I know What I say instead of using GT use predicted values I don't want to say train Variation Adaptor on Mel loss.

**Comment by rishikksh20** [comment] 2020-07-12 09:58
@dathudeptrai Have you start working on `fastspeech2s` ?

**Comment by dathudeptrai** [comment] 2020-07-12 10:01
@rishikksh20 finished but confic of interest so ... i have a plan to play with EATS instead

**Comment by rishikksh20** [comment] 2020-07-12 11:44
@dathudeptrai I actual I am about to complete the implementation but one hurdle is there, the author didn't mention the kernel size, padding, and stride for the first Transpose Convolution layer only mentioned the number of filters i.e 64, do you have any idea regarding this?

**Comment by kan-bayashi** [comment] 2020-07-31 00:44
FastSpeech2 is available now in ESPnet2.
I will close this issue.

**Closed by kan-bayashi** 2020-07-31 00:44 UTC
Labels: Feature request, Help wanted, TTS
