### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by okkteam** [espnet/espnet#2921] opened 2021-01-31 06:17 UTC
**Describe the bug**
When I used aishell data to train a transformer-transducer, 48GB of memory was not enough. In the past, the memory usage was 47909MiB/48600MiB(only espnet training), but today’s training is out of memory. In run.sh `N=0` to use all minibatches.

**Basic environments:**
-GPU: NVIDIA QUADRO RTX 8000 48GB

**transformer-transducer.yaml:**

batch-size: 20
maxlen-in: 800
maxlen-out: 150
criterion: "loss_eps_decay_only"
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: adadelta
epochs: 20
patience: 0
accum-grad: 1
grad-clip: 5.0

etype: transformer
transformer-enc-input-layer: linear
enc-block-arch:
        - type: transformer
          d_hidden: 512
          d_ff: 2048
          heads: 8
          att-dropout-rate: 0.1
enc-block-repeat: 8

dtype: lstm
dlayers: 1
dec-embed-dim: 512
dunits: 512
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1

joint-dim: 512

rnnt-mode: 'rnnt' 
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"

**Error logs**
This error occurs while training:
5.93 GiB (GPU 0; 47.46 GiB total capacity; 27.50 GiB already allocated; 5.21 GiB free; 41.12 GiB reserved in total by PyTorch)

**Comment by okkteam** [comment] 2021-01-31 06:26
![image](https://user-images.githubusercontent.com/49552492/106376439-4f512f00-63d0-11eb-9cdc-d273d09f864b.png)

**Comment by b-flo** [comment] 2021-01-31 08:59
Hi,

We recently switched from LSTMCell to LSTM in RNN-decoder, I guess that could be the reason. However I didn't observe a memory increase with my current settings. Could you give more information about pytorch version, env, etc?

Also, I'm a bit perplexed you need so much memory given your architecture configuration. I'm not too familiar with aishell, do you use the default aishell (w/ configs switched)?

**Comment by okkteam** [comment] 2021-01-31 09:40
> Hi,
> 
> We recently switched from LSTMCell to LSTM in RNN-decoder, I guess that could be the reason. However I didn't observe a memory increase with my current settings. Could you give more information about pytorch version, env, etc?

Thanks for your work, we set a venv from python 3.6.9, torch 1.4.0 and warprnnt-pytorch 0.1. Another error occers just now: `CUDA error: an illegal memory access was encountered`, when I set batchsize is 16.

> Also, I'm a bit perplexed you need so much memory given your architecture configuration. I'm not too familiar with aishell, do you use the default recipe (w/ configs switched)?

The recipe I used from https://github.com/espnet/espnet/issues/2606. They post a not bad CER.

**Comment by okkteam** [comment] 2021-01-31 09:52
GPU Memory Track | 31-Jan-21-17:48:26 | Total Used Memory:8303.7 Mb

+ | 8 * Size:(16, 8, 403, 403)    | Memory: 665.22 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 403, 512)       | Memory: 13.205 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 16)             | Memory: 0.0010 M | <class 'torch.Tensor'>
+ | 8 * Size:(512, 2048)          | Memory: 33.554 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(4233,)              | Memory: 0.0169 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(16, 403, 16, 4233)  | Memory: 1746.8 M | <class 'torch.Tensor'>
+ | 1 * Size:(1, 5000, 512)       | Memory: 10.24 M | <class 'torch.Tensor'>
+ | 34 * Size:(512, 512)           | Memory: 35.651 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:(16, 15)             | Memory: 0.0028 M | <class 'torch.Tensor'>
+ | 2 * Size:(4233, 512)          | Memory: 17.338 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(16, 1, 403)         | Memory: 0.0257 M | <class 'torch.Tensor'>
+ | 4 * Size:(16,)                | Memory: 0.0002 M | <class 'torch.Tensor'>
+ | 78 * Size:(512,)               | Memory: 0.1597 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(512, 83)            | Memory: 0.1699 M | <class 'torch.nn.parameter.Parameter'>
+ | 10 * Size:(2048,)              | Memory: 0.0819 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(16, 1, 403, 403)    | Memory: 10.394 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 403, 83)        | Memory: 6.4222 M | <class 'torch.Tensor'>
+ | 10 * Size:(2048, 512)          | Memory: 41.943 M | <class 'torch.nn.parameter.Parameter'>

At espnet.nets.pytorch_backend.e2e_asr_transducer __init__: line 641Total Used Memory:8303.7 Mb

+ | 102 * Size:(512, 512)           | Memory: 106.95 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 342, 83)        | Memory: 5.4501 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 342, 342)    | Memory: 7.4856 M | <class 'torch.Tensor'>
+ | 234 * Size:(512,)               | Memory: 0.4792 M | <class 'torch.Tensor'>
+ | 102 * Size:(512, 512)           | Memory: 106.95 M | <class 'torch.nn.parameter.Parameter'>
+ | 30 * Size:(2048, 512)          | Memory: 125.82 M | <class 'torch.nn.parameter.Parameter'>
+ | 6 * Size:(4233, 512)          | Memory: 52.015 M | <class 'torch.nn.parameter.Parameter'>
+ | 30 * Size:(2048,)              | Memory: 0.2457 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 342)         | Memory: 0.0218 M | <class 'torch.Tensor'>
+ | 30 * Size:(2048, 512)          | Memory: 125.82 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 13)             | Memory: 0.0024 M | <class 'torch.Tensor'>
+ | 3 * Size:(4233,)              | Memory: 0.0507 M | <class 'torch.Tensor'>
+ | 6 * Size:(4233, 512)          | Memory: 52.015 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 342, 14, 4233)  | Memory: 1297.1 M | <class 'torch.Tensor'>
+ | 24 * Size:(512, 2048)          | Memory: 100.66 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:(512, 83)            | Memory: 0.5099 M | <class 'torch.Tensor'>
+ | 234 * Size:(512,)               | Memory: 0.4792 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:(512, 83)            | Memory: 0.5099 M | <class 'torch.nn.parameter.Parameter'>
+ | 3 * Size:(4233,)              | Memory: 0.0507 M | <class 'torch.nn.parameter.Parameter'>
+ | 1 * Size:(1,)                 | Memory: 4e-06 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 342, 512)       | Memory: 11.206 M | <class 'torch.Tensor'>
+ | 8 * Size:(16, 8, 342, 342)    | Memory: 479.08 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 14)             | Memory: 0.0008 M | <class 'torch.Tensor'>
+ | 30 * Size:(2048,)              | Memory: 0.2457 M | <class 'torch.nn.parameter.Parameter'>
+ | 24 * Size:(512, 2048)          | Memory: 100.66 M | <class 'torch.Tensor'>
- | 8 * Size:(16, 8, 403, 403)    | Memory: 665.22 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 403, 512)       | Memory: 13.205 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 16)             | Memory: 0.0010 M | <class 'torch.Tensor'>
- | 1 * Size:(4233,)              | Memory: 0.0169 M | <class 'torch.nn.parameter.Parameter'>
- | 8 * Size:(512, 2048)          | Memory: 33.554 M | <class 'torch.nn.parameter.Parameter'>
- | 78 * Size:(512,)               | Memory: 0.1597 M | <class 'torch.nn.parameter.Parameter'>
- | 1 * Size:(512, 83)            | Memory: 0.1699 M | <class 'torch.nn.parameter.Parameter'>
- | 10 * Size:(2048,)              | Memory: 0.0819 M | <class 'torch.nn.parameter.Parameter'>
- | 34 * Size:(512, 512)           | Memory: 35.651 M | <class 'torch.nn.parameter.Parameter'>
- | 3 * Size:(16, 15)             | Memory: 0.0028 M | <class 'torch.Tensor'>
- | 2 * Size:(4233, 512)          | Memory: 17.338 M | <class 'torch.nn.parameter.Parameter'>
- | 1 * Size:(16, 1, 403, 403)    | Memory: 10.394 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 403, 83)        | Memory: 6.4222 M | <class 'torch.Tensor'>
- | 10 * Size:(2048, 512)          | Memory: 41.943 M | <class 'torch.nn.parameter.Parameter'>
- | 1 * Size:(16, 1, 403)         | Memory: 0.0257 M | <class 'torch.Tensor'>

At espnet.nets.pytorch_backend.e2e_asr_transducer __init__: line 641Total Used Memory:11667.6Mb
+ | 3 * Size:(16, 471, 83)        | Memory: 7.5058 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 20)             | Memory: 0.0012 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 471, 512)       | Memory: 15.433 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 471, 471)    | Memory: 14.197 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 471)         | Memory: 0.0301 M | <class 'torch.Tensor'>
+ | 8 * Size:(16, 8, 471, 471)    | Memory: 908.66 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 471, 20, 4233)  | Memory: 2551.9 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 19)             | Memory: 0.0036 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 13)             | Memory: 0.0024 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 403, 16, 4233)  | Memory: 1746.8 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 342, 512)       | Memory: 11.206 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 342)         | Memory: 0.0218 M | <class 'torch.Tensor'>
- | 8 * Size:(16, 8, 342, 342)    | Memory: 479.08 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 14)             | Memory: 0.0008 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 342, 83)        | Memory: 5.4501 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 342, 342)    | Memory: 7.4856 M | <class 'torch.Tensor'>

At espnet.nets.pytorch_backend.e2e_asr_transducer __init__: line 641Total Used Memory:16228.9Mb

+ | 1 * Size:(16, 356, 18, 4233)  | Memory: 1736.0 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 18)             | Memory: 0.0011 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 356, 83)        | Memory: 5.6732 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 356, 512)       | Memory: 11.665 M | <class 'torch.Tensor'>
+ | 8 * Size:(16, 8, 356, 356)    | Memory: 519.11 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 356)         | Memory: 0.0227 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 17)             | Memory: 0.0032 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 356, 356)    | Memory: 8.1111 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 471, 83)        | Memory: 7.5058 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 20)             | Memory: 0.0012 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 471, 512)       | Memory: 15.433 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 471, 471)    | Memory: 14.197 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 471)         | Memory: 0.0301 M | <class 'torch.Tensor'>
- | 8 * Size:(16, 8, 471, 471)    | Memory: 908.66 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 342, 14, 4233)  | Memory: 1297.1 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 19)             | Memory: 0.0036 M | <class 'torch.Tensor'>

At espnet.nets.pytorch_backend.e2e_asr_transducer __init__: line 641Total Used Memory:18783.2Mb
+ | 1 * Size:(16, 1, 393, 393)    | Memory: 9.8847 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 393, 83)        | Memory: 6.2628 M | <class 'torch.Tensor'>
+ | 8 * Size:(16, 8, 393, 393)    | Memory: 632.62 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 393)         | Memory: 0.0251 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 393, 512)       | Memory: 12.877 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 393, 18, 4233)  | Memory: 1916.4 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 356, 83)        | Memory: 5.6732 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 356, 512)       | Memory: 11.665 M | <class 'torch.Tensor'>
- | 8 * Size:(16, 8, 356, 356)    | Memory: 519.11 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 356)         | Memory: 0.0227 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 471, 20, 4233)  | Memory: 2551.9 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 356, 356)    | Memory: 8.1111 M | <class 'torch.Tensor'>

At espnet.nets.pytorch_backend.e2e_asr_transducer __init__: line 641Total Used Memory:18783.2Mb

+ | 8 * Size:(16, 8, 352, 352)    | Memory: 507.51 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 13)             | Memory: 0.0024 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 352, 14, 4233)  | Memory: 1335.0 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 352, 352)    | Memory: 7.9298 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 14)             | Memory: 0.0008 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 352)         | Memory: 0.0225 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 352, 83)        | Memory: 5.6094 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 352, 512)       | Memory: 11.534 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 356, 18, 4233)  | Memory: 1736.0 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 18)             | Memory: 0.0011 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 393, 393)    | Memory: 9.8847 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 393, 83)        | Memory: 6.2628 M | <class 'torch.Tensor'>
- | 8 * Size:(16, 8, 393, 393)    | Memory: 632.62 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 17)             | Memory: 0.0032 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 393)         | Memory: 0.0251 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 393, 512)       | Memory: 12.877 M | <class 'torch.Tensor'>

At espnet.nets.pytorch_backend.e2e_asr_transducer __init__: line 641Total Used Memory:18783.2Mb
+ | 8 * Size:(16, 8, 455, 455)    | Memory: 847.97 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 455)         | Memory: 0.0291 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 455, 21, 4233)  | Memory: 2588.5 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 20)             | Memory: 0.0038 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 1, 455, 455)    | Memory: 13.249 M | <class 'torch.Tensor'>
+ | 3 * Size:(16, 455, 83)        | Memory: 7.2508 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 21)             | Memory: 0.0013 M | <class 'torch.Tensor'>
+ | 1 * Size:(16, 455, 512)       | Memory: 14.909 M | <class 'torch.Tensor'>
- | 8 * Size:(16, 8, 352, 352)    | Memory: 507.51 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 13)             | Memory: 0.0024 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 352, 352)    | Memory: 7.9298 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 14)             | Memory: 0.0008 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 1, 352)         | Memory: 0.0225 M | <class 'torch.Tensor'>
- | 3 * Size:(16, 352, 83)        | Memory: 5.6094 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 352, 512)       | Memory: 11.534 M | <class 'torch.Tensor'>
- | 1 * Size:(16, 393, 18, 4233)  | Memory: 1916.4 M | <class 'torch.Tensor'>

At espnet.nets.pytorch_backend.e2e_asr_transducer __init__: line 641Total Used Memory:21373.2Mb

**Comment by b-flo** [comment] 2021-01-31 09:56
> Thanks for your work, we set a venv from python 3.6.9, torch 1.4.0 and warprnnt-pytorch 0.1. Another error occers just now: CUDA error: an illegal memory access was encountered, when I set batchsize is 16.

OK so, this is not an OOM but a illegal memory access. That's weird, I didn't encountered that bug since it was fixed by Mingkun. Could you try training with `transducer-type: warp-rnnt` just to be sure?

> The recipe I used from #2606. They post a not bad CER.

Sorry what I meant was: did you use the default aishell run script (i.e.: egs/aishell/run.sh)? It's to know the data preparation steps

Also thanks for the report, I'll investigate in a short while

**Comment by okkteam** [comment] 2021-01-31 10:06
> > Thanks for your work, we set a venv from python 3.6.9, torch 1.4.0 and warprnnt-pytorch 0.1. Another error occers just now: CUDA error: an illegal memory access was encountered, when I set batchsize is 16.
> 

Yes, that's weird, there was no problem a few days ago... Ok, I will try with `transducer-type: warp-rnnt` in a minute.

> 
> > The recipe I used from #2606. They post a not bad CER.
> 
> Sorry what I meant was: did you use the default aishell run script (i.e.: egs/aishell/run.sh)? It's to know the data preparation steps
> 
> Also thanks for the report, I'll investigate in a short while
Thanks for your help, I just run the default `run.sh` except speed-perturbed.

**Comment by okkteam** [comment] 2021-01-31 10:18
> OK so, this is not an OOM but a illegal memory access. That's weird, I didn't encountered that bug since it was fixed by Mingkun. Could you try training with `transducer-type: warp-rnnt` just to be sure?

Setting `trans-type: warp-rnnt` is work. This error `an illegal memory access was encountered`  occurred when using default `trans-type: warp-transducer`.

**Comment by b-flo** [comment] 2021-01-31 10:36
> Now OOM remains... I have to set the batchsize under 16, but the gpu memory is 48G...

Yeah memory usage exceeding 48Gb seems way too big to me but I'm not sure what's expected with Aishell. Let me familiarize with the corpus and recipe first.

Anyways, if you could train before recent changes, I may have overlooked something in my experiments. I'll try to adress the memory increase at least but it won't make a big difference. We have some items to address memory usage with transducer but it will take a bit of time.

**Comment by b-flo** [comment] 2021-01-31 11:13
@okkteam Are you sure you espnet is up-to-date? In your report I'm confused by : `At espnet.nets.pytorch_backend.e2e_asr_transducer init: line 641Total Used Memory:16228.9Mb`

Current `e2e_asr_transducer.py` has 594 lines.

**Comment by okkteam** [comment] 2021-01-31 11:19
> @okkteam Are you sure you espnet is up-to-date or did you modify it? In your report I'm confused by : `At espnet.nets.pytorch_backend.e2e_asr_transducer init: line 641Total Used Memory:16228.9Mb`
> 
> Current `e2e_asr_transducer.py` has 594 lines.

Sorry，I added some neural network layers in the __init__ to fine-tune the model. I wrote them all under the `if...else` statement, so the number of lines has increased. But when OOM happened, I didn't run it, the model is just a  Transformer-LSTM transducer.

**Comment by qmpzzpmq** [comment] 2021-02-02 06:16
@okkteam hi
I am test this config for @b-flo, Could you tell me how many GPU you use?

**Comment by okkteam** [comment] 2021-02-02 06:19
> @okkteam hi
> I am test this config for @b-flo, Could you tell me how many GPU you use?

Thanks, Just 1 GPU, RTX 8000.

**Comment by qmpzzpmq** [comment] 2021-02-02 06:22
I change your config a little bit for running as flowing:
batch-size: 10
maxlen-in: 800
maxlen-out: 150
criterion: "loss_eps_decay_only"
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: adadelta
epochs: 20
patience: 0
accum-grad: 1
grad-clip: 5.0

etype: custom
# transformer-enc-input-layer: vgg2l
enc-block-arch:
        - type: transformer
          d_hidden: 512
          d_ff: 2048
          heads: 8
          att-dropout-rate: 0.1
enc-block-repeat: 8

dtype: lstm
dlayers: 1
dec-embed-dim: 512
dunits: 512
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1

joint-dim: 512

# rnnt-mode: 'rnnt'
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"

it is seems ok for me running several steps with only 1 2080ti gpu. But suddenly stopped with 4 gpu. I don't what's going on with it. But I will talk with @b-flo later.

**Comment by b-flo** [comment] 2021-02-02 09:45
@okkteam From what @qmpzzpmq and I tested, for `batchsize: 20` you would need (roughly) ~20Gb for peak memory usage and average memory usage should be below that. Please check the issue isn't related to the layers you added.

About multi-GPU, I pinpointed the issue. It will be fixed shortly, sorry about that.

**Comment by okkteam** [comment] 2021-02-02 09:52
> @okkteam From what @qmpzzpmq and I tested, for `batchsize: 20` you would need (roughly) ~20Gb for peak memory usage and average memory usage should be below that. Please check the issue isn't related to the layers you added.
> 
> About multi-GPU, I pinpointed the issue. It will be fixed shortly, sorry about that.

Thanks for your help and @qmpzzpmq, I will check that.

**Comment by b-flo** [comment] 2021-02-02 10:23
I'm closing the issue but feel free to re-open if you have new information / reports!

**Closed by b-flo** 2021-02-02 10:23 UTC
Labels: Discussion, RNNT
