### ISSUE TITLE
Is it possible training a recipe ( ljspeech) in colab?

### ISSUE THREAD

**Issue by Manjur-LU** [espnet/espnet#3261] opened 2021-05-31 21:25 UTC

**Comment by kan-bayashi** [comment] 2021-06-17 02:40
You can do it but the available training time is limited.
This is an example.
https://colab.research.google.com/github/espnet/interspeech2019-tutorial/blob/master/notebooks/interspeech2019_tts/interspeech2019_tts.ipynb
This is based on ESPnet1, but basically you can do the same thing with ESPnet2.

**Comment by Manjur-LU** [comment] 2021-06-19 15:29
I found this error @kan-bayashi 


Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/espnet/espnet2/bin/tts_train.py", line 2, in <module>
    from espnet2.tasks.tts import TTSTask
  File "/content/espnet/espnet2/tasks/tts.py", line 17, in <module>
    from espnet2.tasks.abs_task import AbsTask
  File "/content/espnet/espnet2/tasks/abs_task.py", line 60, in <module>
    from espnet2.train.iterable_dataset import IterableESPnetDataset
  File "/content/espnet/espnet2/train/iterable_dataset.py", line 67, in <module>
    class IterableESPnetDataset(IterableDataset):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/usr/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_typing.py", line 371, in _dp_init_subclass
    ", but found {}".format(sub_cls.__name__, _type_repr(hints['return'])))
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of IterableESPnetDataset, but found typing.Iterable[typing.Tuple[typing.Union[str, int], typing.Dict[str, numpy.ndarray]]]
# Accounting: time=7 threads=1
# Ended (code 1) at Sat Jun 19 15:18:35 UTC 2021, elapsed time 7 seconds

**Comment by Manjur-LU** [comment] 2021-06-19 15:31
@kan-bayashi   this is my colab code 
 https://colab.research.google.com/drive/1nwg4qgvy5A3aerfGQvIL96no_I-2Gwgh?usp=sharing

**Comment by kan-bayashi** [comment] 2021-06-22 00:51
Caused by pytorch >= 1.9.
Fixed in #3310

**Closed by kan-bayashi** 2021-06-22 00:51 UTC
Labels: Question
