### ISSUE TITLE
espnet1 transducer bug report

### ISSUE THREAD

**Issue by qmpzzpmq** [espnet/espnet#3548] opened 2021-09-03 01:17 UTC
@b-flo I think I meet a bug in VIVOS.

Pytorch: 1.9
CUDA: 11.1

The script is running with all default setting and I just add two line as followed in to train.yaml.
`
noam-lr: 5.0
noam-adim: 4
`
I copy from other transducer config, but there still are some bug log:

> Exception in main training loop: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Traceback (most recent call last):
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/groups/4/gcc50479/tanghaoyu/espnet/espnet/asr/pytorch_backend/asr.py", line 235, in update
    self.update_core()
  File "/groups/4/gcc50479/tanghaoyu/espnet/espnet/asr/pytorch_backend/asr.py", line 209, in update_core
    loss.backward()
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/groups/4/gcc50479/tanghaoyu/espnet/egs/vivos/asr1/../../../espnet/bin/asr_train.py", line 639, in <module>
    main(sys.argv[1:])
  File "/groups/4/gcc50479/tanghaoyu/espnet/egs/vivos/asr1/../../../espnet/bin/asr_train.py", line 625, in main
    train(args)
  File "/groups/4/gcc50479/tanghaoyu/espnet/espnet/asr/pytorch_backend/asr.py", line 967, in train
    trainer.run()
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/groups/4/gcc50479/tanghaoyu/espnet/espnet/asr/pytorch_backend/asr.py", line 235, in update
    self.update_core()
  File "/groups/4/gcc50479/tanghaoyu/espnet/espnet/asr/pytorch_backend/asr.py", line 209, in update_core
    loss.backward()
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/acc12416pz/anaconda3/envs/tespnet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

But I check the log, it semms only happen in the last batch.

**Comment by b-flo** [comment] 2021-09-03 11:26
I'm removing the RNNT tag for now. It's related to torch and CUDA and the error may be trigerred by an operation in Transducer but it could happen for other models. We're discussing the issue off the list, I'll report our findings.

**Comment by b-flo** [comment] 2021-09-06 06:12
It seems related to @qmpzzpmq's cluster CUDA loader and I couldn't reproduce the issue with different setup.
I'm closing the issue, I'll reopen if needed.

**Closed by b-flo** 2021-09-06 06:12 UTC
Labels: Bug, Discussion
