### ISSUE TITLE
when run.sh how can I choose my conda environment?

### ISSUE THREAD

**Issue by xcrpkuss** [espnet/espnet#2241] opened 2020-07-30 06:56 UTC
![image](https://user-images.githubusercontent.com/56855140/88890571-645bd280-d274-11ea-9ace-ee13751c3055.png)
I try "./run.sh --backend chainer" in egs/an4/asr1,but have the bug above.
the log said ：
“Traceback (most recent call last):
  File "/home/x50015769/ctc/espnet-master/egs/an4/asr1/../../../utils/copy-feats.py", line 6, in <module>
    from espnet.transform.transformation import Transformation
ModuleNotFoundError: No module named 'espnet'”
but in my conde environment,I can import this pakeage.
![image](https://user-images.githubusercontent.com/56855140/88890912-e1874780-d274-11ea-98d3-d0d1491d6880.png)

**Comment by kamo-naoyuki** [comment] 2020-07-30 08:21
I wrote about the setup flow at https://espnet.github.io/espnet/faq.html
so, you can choose your python by rewriting `path.sh`.

Sorry for the complicated system, but this is necessary.

I recently updated the system about the python environment, so I' like to ask you that which version do you use. The current system is more flexible: https://espnet.github.io/espnet/installation.html#step-2-installation-of-espnet

I guess when you installed espnet, you didn't deactivate your conda. In this case, espnet is installed in the conda and you get the error. This problem was fixed in my updates.

**Comment by kan-bayashi** [comment] 2020-07-30 08:25
Maybe this is caused by `/path/to/kaldi/tools/env.sh`.
Could you try to remove `/path/to/kaldi/tools/python/python`?

**Comment by kamo-naoyuki** [comment] 2020-07-30 08:31
@kan-bayashi Kaldi creates it by default? I forgot it.
but, the conda activate is called after kaldi/tools/env.sh, so it doesn't affect in my understanding?

**Comment by kan-bayashi** [comment] 2020-07-30 08:34
> Kaldi creates it by default? I forgot it.

Yes.

> but, the conda activate is called after kaldi/tools/env.sh, so it doesn't affect in my understanding?

I think so, but some people reported this can fix a similar issue.
https://github.com/espnet/espnet/issues/1656#issuecomment-601033168

**Comment by kamo-naoyuki** [comment] 2020-07-30 09:01
It's impossible. Even if the activate doen't work by some reason, kaldi/tools/python/python can't affect because we always invoke python as `python3`, not `python`.

**Comment by kamo-naoyuki** [comment] 2020-07-30 09:08
And, i think we should remove the part of kaldi/tools/env.sh from path.sh. It just sets  as `python` to `/usr/bin/python2.7`, but it's unnecessary for us.  All kaldi scripts now supports python3 and also we don't use such scripts in kaldi.

**Comment by xcrpkuss** [comment] 2020-07-30 09:25
> 我在[https://espnet.github.io/espnet/faq.html上](https://espnet.github.io/espnet/faq.html)介绍了设置流程，
> 因此，您可以通过重写选择python `path.sh`。
> 
> 很抱歉，系统很复杂，但这是必需的。
> 
> 我最近更新了有关python环境的系统，所以我想问您使用哪个版本。当前系统更加灵活：[https](https://espnet.github.io/espnet/installation.html#step-2-installation-of-espnet) : [//espnet.github.io/espnet/installation.html#step-2-installation-of-espnet](https://espnet.github.io/espnet/installation.html#step-2-installation-of-espnet)
> 
> 我想当您安装espnet时，并没有停用conda。在这种情况下，espnet已安装在conda中，并且您会收到错误消息。我的更新中已解决此问题。

Thank you！I solve this problem by rewrite path.sh!
And I use "Option D) using the existing Python/Anaconda without creating new environment",and install successfully.Thank you your great job and great project!

**Closed** 2020-07-30 12:06 UTC
Labels: Question
