### ISSUE TITLE
TypeError: Expected 'Iterator' as the return annotation for `__iter__` of IterableESPnetDataset, but found typing.Iterable[typing.Tuple[typing.Union[str, int], typing.Dict[str, numpy.ndarray]]]

### ISSUE THREAD

**Issue by vumichien** [espnet/espnet#3309] opened 2021-06-21 13:36 UTC
I got this error when running example in colab 
espnet==0.9.7 
parallel_wavegan==0.4.8
![image](https://user-images.githubusercontent.com/31467068/122771365-52967a00-d2e1-11eb-830a-c17658e4e3f6.png)

**Comment by kan-bayashi** [comment] 2021-06-22 00:49
Caused by pytorch >= 1.9.
Fixed in #3310

**Closed by kan-bayashi** 2021-06-22 00:49 UTC
Labels: Bug
